/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;

/**
 *
 * @author adria
 */
public class SecretariasRegistradas extends javax.swing.JFrame {

    /**
     * Creates new form SecretariasRegistradas
     */
    public SecretariasRegistradas() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/media/logo.png")).getImage());
        this.setLocationRelativeTo(null);
        registroSecretariaTable.getTableHeader().setFont(new Font("Montserrat", Font.BOLD, 12));
        registroSecretariaTable.getTableHeader().setOpaque(false);
        registroSecretariaTable.getTableHeader().setOpaque(false);
        registroSecretariaTable.getTableHeader().setForeground(new Color(47,72,90));
        registroSecretariaTable.setRowHeight(25);//scroll
    }

    AgregarSecretaria agregar = new AgregarSecretaria();
    EditarSecretaria editar = new EditarSecretaria();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eliminarButton = new javax.swing.JButton();
        agregarButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        registroSecretariaTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eliminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Eliminar.png"))); // NOI18N
        eliminarButton.setBorder(null);
        eliminarButton.setContentAreaFilled(false);
        eliminarButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Eliminar – 1.png"))); // NOI18N
        eliminarButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Eliminar – 1.png"))); // NOI18N
        getContentPane().add(eliminarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 450, 100, 100));

        agregarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Agregar.png"))); // NOI18N
        agregarButton.setBorder(null);
        agregarButton.setContentAreaFilled(false);
        agregarButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Agregar – 1.png"))); // NOI18N
        agregarButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Agregar – 1.png"))); // NOI18N
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(agregarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 190, 100, 100));

        editarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Editar.png"))); // NOI18N
        editarButton.setBorder(null);
        editarButton.setContentAreaFilled(false);
        editarButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Editar – 1.png"))); // NOI18N
        editarButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Editar – 1.png"))); // NOI18N
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 320, 100, 100));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/home.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        registroSecretariaTable.setBackground(new java.awt.Color(255, 255, 250));
        registroSecretariaTable.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        registroSecretariaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Secretaria", "Matrícula", "Nombre", "Facultad", "Contraseña"
            }
        ));
        jScrollPane1.setViewportView(registroSecretariaTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 1150, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Visualizar secretarias – 1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        MenuAdministrador MenuAdmin = new MenuAdministrador();
        this.setVisible(false);
        MenuAdmin.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        this.setVisible(false);
        agregar.setVisible(true);
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        this.setVisible(false);
        editar.setVisible(true);
    }//GEN-LAST:event_editarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretariasRegistradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretariasRegistradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretariasRegistradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretariasRegistradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecretariasRegistradas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable registroSecretariaTable;
    // End of variables declaration//GEN-END:variables
}
