/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;

/**
 *
 * @author adria
 */
public class Estatus extends javax.swing.JFrame {

    /**
     * Creates new form Estatus
     */
    public Estatus() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/media/logo.png")).getImage());
        this.setLocationRelativeTo(null);
        estatusTable.getTableHeader().setFont(new Font("Montserrat", Font.BOLD, 12));
        estatusTable.getTableHeader().setOpaque(false);
        estatusTable.getTableHeader().setOpaque(false);
        estatusTable.getTableHeader().setForeground(new Color(47,72,90));
        estatusTable.setRowHeight(25);//scroll
    }
    EditarAlumno editar = new EditarAlumno();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarTextField = new javax.swing.JTextField();
        homeButton = new javax.swing.JButton();
        filtroComboBox = new javax.swing.JComboBox<>();
        buscarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        estatusTable = new javax.swing.JTable();
        editarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscarTextField.setBackground(new java.awt.Color(220, 236, 246));
        buscarTextField.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        buscarTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 236, 246), 3, true));
        buscarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(buscarTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 830, 60));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/home.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        filtroComboBox.setBackground(new java.awt.Color(220, 236, 246));
        filtroComboBox.setFont(new java.awt.Font("Tw Cen MT", 0, 28)); // NOI18N
        filtroComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Folio", "Fecha de solicitud", "Matrícula", "Nombre", "Estatus" }));
        filtroComboBox.setBorder(null);
        filtroComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(filtroComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 230, 60));

        buscarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/lupaa.png"))); // NOI18N
        buscarButton.setBorder(null);
        buscarButton.setContentAreaFilled(false);
        buscarButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/lupa.png"))); // NOI18N
        buscarButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/media/lupa.png"))); // NOI18N
        getContentPane().add(buscarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 140, 70, 60));

        estatusTable.setBackground(new java.awt.Color(255, 255, 250));
        estatusTable.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        estatusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Tramite", "Folio", "Fecha de solicitud", "Matrícula", "Nombre", "Estatus", "*Motivo de rechazo"
            }
        ));
        jScrollPane1.setViewportView(estatusTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 1140, 450));

        editarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Editar.png"))); // NOI18N
        editarButton.setBorder(null);
        editarButton.setContentAreaFilled(false);
        editarButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Editar – 1.png"))); // NOI18N
        editarButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Editar – 1.png"))); // NOI18N
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 220, 100, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Estatus – 1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        MenuSecretariaa MenuSecre = new MenuSecretariaa();
        this.setVisible(false);
        MenuSecre.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void buscarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarTextFieldActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        this.setVisible(false);
        editar.setVisible(true);
    }//GEN-LAST:event_editarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField buscarTextField;
    private javax.swing.JButton editarButton;
    private javax.swing.JTable estatusTable;
    private javax.swing.JComboBox<String> filtroComboBox;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
