/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Iniciador.RMI;
import Interfaces.IEstudiante;
import Interfaces.ITramite;
import Interfaces.ITramiteController;
import java.awt.Color;
import java.awt.Font;
import java.rmi.RemoteException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adria
 */
public class Tramite extends javax.swing.JFrame {

    /**
     * Creates new form Tramite
     */
    public Tramite() {
        initComponents();
        refrescarTabla();
        setIconImage(new ImageIcon(getClass().getResource("/media/logo.png")).getImage());
        this.setLocationRelativeTo(null);
        tramiteTable.getTableHeader().setFont(new Font("Montserrat", Font.BOLD, 12));
        tramiteTable.getTableHeader().setOpaque(false);
        tramiteTable.getTableHeader().setOpaque(false);
        tramiteTable.getTableHeader().setForeground(new Color(47, 72, 90));
        tramiteTable.setRowHeight(25);//scroll
    }

    AgregarTramite agregar = new AgregarTramite();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eliminarButton = new javax.swing.JButton();
        agregarButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tramiteTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eliminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Eliminar.png"))); // NOI18N
        eliminarButton.setBorder(null);
        eliminarButton.setContentAreaFilled(false);
        eliminarButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Eliminar – 1.png"))); // NOI18N
        eliminarButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Eliminar – 1.png"))); // NOI18N
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 450, 100, 100));

        agregarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Agregar.png"))); // NOI18N
        agregarButton.setBorder(null);
        agregarButton.setContentAreaFilled(false);
        agregarButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Agregar – 1.png"))); // NOI18N
        agregarButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Agregar – 1.png"))); // NOI18N
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(agregarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 190, 100, 100));

        editarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Editar.png"))); // NOI18N
        editarButton.setBorder(null);
        editarButton.setContentAreaFilled(false);
        editarButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Editar – 1.png"))); // NOI18N
        editarButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Editar – 1.png"))); // NOI18N
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 320, 100, 100));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/home.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        tramiteTable.setBackground(new java.awt.Color(255, 255, 250));
        tramiteTable.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tramiteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Tramite", "Folio", "Fecha de solicitud", "Matrícula", "Nombre", "Estatus"
            }
        ));
        jScrollPane1.setViewportView(tramiteTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 1150, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/tramites.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void refrescarTabla() {
        try {
            Vector<Vector> datos = new Vector<>();

            List<ITramite> listaTramite = RMI.getITramiteController().list();
            List<IEstudiante> listaEstudiante = RMI.getIEstudianteController().list();

            for (ITramite tramite : listaTramite) {
                Vector registro = new Vector();

                registro.add(tramite.getFolio());
                registro.add(tramite.getFecha());
                registro.add(tramite.getMatricula());
                for (IEstudiante estudiante : listaEstudiante) {
                    if (estudiante.getMatricula().equals(tramite.getMatricula())) {
                        registro.add(estudiante.getNombres() + " " + estudiante.getApellidoPaterno() + " " + estudiante.getApellidoMaterno());
                    }
                }
                registro.add(tramite.getEstado());

                datos.add(registro);
            }

            Vector<String> columnas = new Vector<>();
            columnas.add("Folio");
            columnas.add("Fecha de solicitud");
            columnas.add("Matrícula");
            columnas.add("Nombre");
            columnas.add("Estatus");

            tramiteTable.setModel(new DefaultTableModel(datos, columnas));
        } catch (RemoteException ex) {
            Logger.getLogger(Tramite.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        this.setVisible(false);
        agregar.setVisible(true);
        refrescarTabla();
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        try {
            int filaSeleccionada = tramiteTable.getSelectedRow();
            if (filaSeleccionada == -1) {
                return;
            }
            String folio = (String) tramiteTable.getValueAt(filaSeleccionada, 0);
            ITramite tramite = RMI.getITramiteController().findOne(folio);

            if (tramite.getFolio() == null) {
                JOptionPane.showMessageDialog(this, "Folio no encontrado.\n" + "Probablemente el folio fue eliminada previamente.", "Folio no encontrado", JOptionPane.ERROR_MESSAGE);
                refrescarTabla();
                return;
            }
            EditarTramite editarTramite = new EditarTramite(tramite);
            this.setVisible(false);
            editarTramite.setVisible(true);
            refrescarTabla();
        } catch (RemoteException ex) {
            Logger.getLogger(Tramite.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editarButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        MenuSecretariaa MenuSecre = new MenuSecretariaa();
        this.setVisible(false);
        MenuSecre.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        try {
            int filaSeleccionada = tramiteTable.getSelectedRow();
            if (filaSeleccionada == -1) {
                return;
            }
            int confirmacion = JOptionPane.showConfirmDialog(
                    this,
                    "Usted está a punto de eliminar una solicitud de impresión.\n" + "¿Desea continuar?",
                    "Eliminar secretaria",
                    JOptionPane.YES_NO_OPTION);
            if (confirmacion != JOptionPane.YES_OPTION) {
                return;
            }
            String folio = (String) tramiteTable.getValueAt(filaSeleccionada, 0);
            int respuesta = RMI.getITramiteController().delete(folio);
            
            if (respuesta == ITramiteController.DELETE_EXITO) {
                JOptionPane.showMessageDialog(this,
                        "Tramite eliminado con éxito.",
                        "Operación exitosa",
                        JOptionPane.INFORMATION_MESSAGE);
                refrescarTabla();
            } else if (respuesta == ITramiteController.DELETE_SIN_EXITO) {
                JOptionPane.showMessageDialog(this,
                        "No fue posible completar la operación.",
                        "Operación no exitosa",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Tramite.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_eliminarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tramite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tramite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tramite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tramite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tramite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tramiteTable;
    // End of variables declaration//GEN-END:variables
}
