/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Iniciador.RMI;
import Interfaces.ICarrera;
import Interfaces.IEstudianteController;
import Interfaces.IEstudiante;
import Interfaces.IFacultad;
import java.awt.Color;
import java.awt.Font;
import java.rmi.RemoteException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AlumnosRegistrados extends javax.swing.JFrame {

    public int idFacultad;
    public int ALUMNOS = 1;

    public AlumnosRegistrados(int idFacultad) {
        initComponents();
        this.idFacultad = idFacultad;
        refrescarTabla();
        setIconImage(new ImageIcon(getClass().getResource("/media/logo.png")).getImage());
        this.setLocationRelativeTo(null);
        registroAlumnoTable.getTableHeader().setFont(new Font("Montserrat", Font.BOLD, 12));
        registroAlumnoTable.getTableHeader().setOpaque(false);
        registroAlumnoTable.getTableHeader().setOpaque(false);
        registroAlumnoTable.getTableHeader().setForeground(new Color(47, 72, 90));
        registroAlumnoTable.setRowHeight(25);//scroll

    }

    public void refrescarTabla() {
        try {
            Vector<Vector> datos = new Vector<>();
            List<IEstudiante> listaEstudiantes = RMI.getIEstudianteController().list();
            List<IFacultad> listaFacultades = RMI.getIFacultadController().list();
            List<ICarrera> listaCarreras = RMI.getICarreraController().list();

            for (IEstudiante estudiante : listaEstudiantes) {
                Vector registro = new Vector();

                if (estudiante.getIdFacultad() == idFacultad) {
                    registro.add(estudiante.getMatricula());
                    registro.add(estudiante.getApellidoPaterno());
                    registro.add(estudiante.getApellidoMaterno());
                    registro.add(estudiante.getNombres());
                    for (IFacultad facultad : listaFacultades) {
                        if (estudiante.getIdFacultad() == facultad.getId()) {
                            registro.add(facultad.getFacultad());
                        }
                    }

                    for (ICarrera carrera : listaCarreras) {
                        if (estudiante.getIdCarrera() == carrera.getIdCarrera()) {
                            registro.add(carrera.getNombreCarrera());
                        }
                    }
                    datos.add(registro);
                }

            }

            Vector<String> columnas = new Vector<>();
            columnas.add("Matrícula");
            columnas.add("Apellido paterno");
            columnas.add("Apellido materno");
            columnas.add("Nombre");
            columnas.add("Facultad");
            columnas.add("Carrera");

            registroAlumnoTable.setModel(new DefaultTableModel(datos, columnas));
        } catch (RemoteException ex) {
            Logger.getLogger(AlumnosRegistrados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eliminarButton = new javax.swing.JButton();
        agregarButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        registroAlumnoTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eliminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Eliminar.png"))); // NOI18N
        eliminarButton.setBorder(null);
        eliminarButton.setContentAreaFilled(false);
        eliminarButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Eliminar – 1.png"))); // NOI18N
        eliminarButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Eliminar – 1.png"))); // NOI18N
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 450, 100, 100));

        agregarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Agregar.png"))); // NOI18N
        agregarButton.setBorder(null);
        agregarButton.setContentAreaFilled(false);
        agregarButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Agregar – 1.png"))); // NOI18N
        agregarButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Agregar – 1.png"))); // NOI18N
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(agregarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 190, 100, 100));

        editarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Editar.png"))); // NOI18N
        editarButton.setBorder(null);
        editarButton.setContentAreaFilled(false);
        editarButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Editar – 1.png"))); // NOI18N
        editarButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Editar – 1.png"))); // NOI18N
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 320, 100, 100));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/home.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        registroAlumnoTable.setAutoCreateRowSorter(true);
        registroAlumnoTable.setBackground(new java.awt.Color(255, 255, 250));
        registroAlumnoTable.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        registroAlumnoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Alumno", "ApellidoPaterno", "ApellidoMaterno", "Nombre", "Facultad", "Carrera", "Foto", "Firma"
            }
        ));
        jScrollPane1.setViewportView(registroAlumnoTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 1150, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Alumnos reg – 3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        AgregarAlumno agregar = new AgregarAlumno(idFacultad);
        this.setVisible(false);
        agregar.setVisible(true);
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        try {
            int filaSeleccionada = registroAlumnoTable.getSelectedRow();
            if (filaSeleccionada == -1) {
                return;
            }
            String matricula = (String) registroAlumnoTable.getValueAt(filaSeleccionada, 0);
            IEstudiante estudiante = RMI.getIEstudianteController().findOne(matricula);

            if (estudiante.getMatricula() == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "Matrícula no encontrada.\n" + "Probablemente la matrícula fue eliminada previamente.",
                        "Matrícula no encontrada",
                        JOptionPane.ERROR_MESSAGE);
                refrescarTabla();
                return;
            }

            EditarAlumno editarAlumno = new EditarAlumno(estudiante, idFacultad, ALUMNOS);
            this.setVisible(false);
            editarAlumno.setVisible(true);
            refrescarTabla();

        } catch (RemoteException ex) {
            Logger.getLogger(AlumnosRegistrados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editarButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        MenuSecretaria MenuSecre = new MenuSecretaria(idFacultad);
        this.setVisible(false);
        MenuSecre.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        try {
            int filaSeleccionada = registroAlumnoTable.getSelectedRow();
            if (filaSeleccionada == -1) {
                return;
            }
            int confirmacion = JOptionPane.showConfirmDialog(
                    this, "Usted está a punto de eliminar un alumno.\n" + "¿Desea continuar?",
                    "Eliminar alumno",
                    JOptionPane.YES_NO_OPTION);
            if (confirmacion != JOptionPane.YES_OPTION) {
                return;
            }

            String matricula = (String) registroAlumnoTable.getValueAt(filaSeleccionada, 0);

            int respuesta = RMI.getIEstudianteController().delete(matricula);

            if (respuesta == IEstudianteController.DELETE_EXITO) {
                JOptionPane.showMessageDialog(
                        this,
                        "Alumno eliminado con éxito.",
                        "Operación exitosa",
                        JOptionPane.INFORMATION_MESSAGE);
                refrescarTabla();
            } else if (respuesta == IEstudianteController.DELETE_ESTUDIANTE_INEXISTENTE) {
                JOptionPane.showMessageDialog(
                        this,
                        "Alumno no encontrado.",
                        "Operación sin éxito",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Operación incompleta.\n" + "Probablemente el alumno fue eliminado previamente.",
                        "Operación incompleta",
                        JOptionPane.ERROR_MESSAGE);
                refrescarTabla();
            }

        } catch (RemoteException ex) {
            Logger.getLogger(AlumnosRegistrados.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_eliminarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnosRegistrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnosRegistrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnosRegistrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnosRegistrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable registroAlumnoTable;
    // End of variables declaration//GEN-END:variables
}
