package gui;

import Iniciador.RMI;
import Interfaces.IEstudiante;
import Interfaces.ITramite;
import Interfaces.ITramiteController;
import java.rmi.RemoteException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class EditarTramite extends javax.swing.JFrame {

    public int idFacultad;
    public String folioAnterior;
    private ITramite tramite;

    public EditarTramite(ITramite tramite, int idFacultad) {
        initComponents();
        this.tramite = tramite;
        this.idFacultad = idFacultad;
        try {
            this.folioAnterior = tramite.getFolio();
        } catch (RemoteException ex) {
            Logger.getLogger(EditarTramite.class.getName()).log(Level.SEVERE, null, ex);
        }
        setIconImage(new ImageIcon(getClass().getResource("/media/logo.png")).getImage());
        this.setLocationRelativeTo(null);

        try {
            folioTextField.setText(tramite.getFolio());
            matriculaTextField.setText(tramite.getMatricula());
            String matricula = matriculaTextField.getText();
            IEstudiante estudiante = RMI.getIEstudianteController().findOne(matricula);
            nombreTextField.setText(estudiante.getNombres() + " " + estudiante.getApellidoPaterno() + " " + estudiante.getApellidoMaterno());

        } catch (RemoteException ex) {
            Logger.getLogger(EditarTramite.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atrasButton = new javax.swing.JButton();
        nombreTextField = new javax.swing.JTextField();
        matriculaTextField = new javax.swing.JTextField();
        folioTextField = new javax.swing.JTextField();
        guardarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/atras.png"))); // NOI18N
        atrasButton.setBorder(null);
        atrasButton.setContentAreaFilled(false);
        atrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasButtonActionPerformed(evt);
            }
        });
        getContentPane().add(atrasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 50, -1));

        nombreTextField.setEditable(false);
        nombreTextField.setBackground(new java.awt.Color(220, 236, 246));
        nombreTextField.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        nombreTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 236, 246), 3, true));
        getContentPane().add(nombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 800, 90));

        matriculaTextField.setBackground(new java.awt.Color(220, 236, 246));
        matriculaTextField.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        matriculaTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 236, 246), 3, true));
        matriculaTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                matriculaTextFieldMouseExited(evt);
            }
        });
        getContentPane().add(matriculaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 370, 90));

        folioTextField.setBackground(new java.awt.Color(220, 236, 246));
        folioTextField.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        folioTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 236, 246), 3, true));
        getContentPane().add(folioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 370, 90));

        guardarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Guardar_1.png"))); // NOI18N
        guardarButton.setBorder(null);
        guardarButton.setContentAreaFilled(false);
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(guardarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 200, 50));

        cancelarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/cancelar.png"))); // NOI18N
        cancelarButton.setBorder(null);
        cancelarButton.setContentAreaFilled(false);
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, 200, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/EditarTram.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasButtonActionPerformed
        Tramite tramite = new Tramite(idFacultad);
        this.setVisible(false);
        tramite.setVisible(true);
    }//GEN-LAST:event_atrasButtonActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        try {
            String matricula = matriculaTextField.getText();
            String folio = folioTextField.getText();

            IEstudiante estudiante = RMI.getIEstudianteController().findOne(matricula);
            if (estudiante.getMatricula() == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "Ingrese una matrícula válida.",
                        "Validación",
                        JOptionPane.ERROR_MESSAGE);
                folioTextField.requestFocus();
                return;
            }
            
            if (folio.length() == 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "Ingrese el folio",
                        "Validación",
                        JOptionPane.ERROR_MESSAGE);
                folioTextField.requestFocus();
                return;
            } else {
                tramite.setFolio(folio);
            }

            if (matricula.length() != 9) {
                JOptionPane.showMessageDialog(
                        this,
                        "Ingrese la matrícula.",
                        "Validación",
                        JOptionPane.ERROR_MESSAGE);
                matriculaTextField.requestFocus();
                return;
            } else {
                tramite.setMatricula(matricula);
                SimpleDateFormat fechaActual = new SimpleDateFormat("dd-MM-yyyy");
                String fecha = fechaActual.format(new Date());
                tramite.setFecha(fecha);
                tramite.setEstado("Pendiente");
            }

            int respuesta = RMI.getITramiteController().update(tramite, folioAnterior);
            if (respuesta == ITramiteController.UPDATE_EXITO) {
                JOptionPane.showMessageDialog(this,
                        "El trámite ha sido modificado exitosamente.",
                        "Cambios registrados",
                        JOptionPane.INFORMATION_MESSAGE);
                Tramite tramites = new Tramite(idFacultad);
                this.setVisible(false);
                tramites.setVisible(true);
            } else if (respuesta == ITramiteController.UPDATE_FOLIO_INEXISTE) {
                JOptionPane.showMessageDialog(this,
                        "El folio ingresado no se encuentra registrado.",
                        "Operación no exitosa",
                        JOptionPane.ERROR_MESSAGE);
            } else if (respuesta == ITramiteController.UPDATE_SIN_EXITO) {
                JOptionPane.showMessageDialog(this,
                        "No fue posible registrar el cambio.",
                        "Operación no exitosa",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(EditarTramite.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        Tramite tramite = new Tramite(idFacultad);
        this.setVisible(false);
        tramite.setVisible(true);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void matriculaTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matriculaTextFieldMouseExited
        try {
            String matricula = matriculaTextField.getText();
            IEstudiante estudiante = RMI.getIEstudianteController().findOne(matricula);
            if (estudiante.getNombres() != null) {
                nombreTextField.setText(estudiante.getNombres() + " " + estudiante.getApellidoPaterno() + " " + estudiante.getApellidoMaterno());
            }
        } catch (RemoteException ex) {
            Logger.getLogger(AgregarTramite.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_matriculaTextFieldMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarTramite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarTramite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarTramite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarTramite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField folioTextField;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField matriculaTextField;
    private javax.swing.JTextField nombreTextField;
    // End of variables declaration//GEN-END:variables
}
