/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Iniciador.RMI;
import Interfaces.ICarrera;
import Interfaces.ICarreraController;
import Interfaces.IFacultad;
import java.awt.Color;
import java.awt.Font;
import java.rmi.RemoteException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adria
 */
public class CarrerasRegistradas extends javax.swing.JFrame {

    public CarrerasRegistradas() {
        initComponents();
        refrescarTabla();
        setIconImage(new ImageIcon(getClass().getResource("/media/logo.png")).getImage());
        this.setLocationRelativeTo(null);
        registroCarreraTable.getTableHeader().setFont(new Font("Montserrat", Font.BOLD, 14));
        registroCarreraTable.getTableHeader().setOpaque(false);
        registroCarreraTable.getTableHeader().setOpaque(false);
        registroCarreraTable.getTableHeader().setForeground(new Color(47, 72, 90));
        registroCarreraTable.setRowHeight(25);//scroll
    }

    AgregarCarrera agregar = new AgregarCarrera();

    public void refrescarTabla() {
        try {
            Vector<Vector> datos = new Vector<>();

            List<ICarrera> listaCarrera;
            listaCarrera = RMI.getICarreraController().list();
            List<IFacultad> listaFacultad;
            listaFacultad = RMI.getIFacultadController().list();

            for (ICarrera iCarrera : listaCarrera) {
                Vector registro = new Vector();
                for (IFacultad iFacultad : listaFacultad) {
                    if (iCarrera.getIdFacultad() == iFacultad.getId()) {
                        registro.add(iFacultad.getFacultad());
                    }
                }
                registro.add(iCarrera.getNombreCarrera());
                datos.add(registro);
            }
            Vector<String> columnas = new Vector<>();
            columnas.add("Facultad");
            columnas.add("Carrera");
            registroCarreraTable.setModel(new DefaultTableModel(datos, columnas));
        } catch (RemoteException ex) {
            Logger.getLogger(CarrerasRegistradas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eliminarButton = new javax.swing.JButton();
        agregarButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        registroCarreraTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eliminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Eliminar.png"))); // NOI18N
        eliminarButton.setBorder(null);
        eliminarButton.setContentAreaFilled(false);
        eliminarButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Eliminar – 1.png"))); // NOI18N
        eliminarButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Eliminar – 1.png"))); // NOI18N
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 450, 100, 100));

        agregarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Agregar.png"))); // NOI18N
        agregarButton.setBorder(null);
        agregarButton.setContentAreaFilled(false);
        agregarButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Agregar – 1.png"))); // NOI18N
        agregarButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Agregar – 1.png"))); // NOI18N
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(agregarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 190, 100, 100));

        editarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Editar.png"))); // NOI18N
        editarButton.setBorder(null);
        editarButton.setContentAreaFilled(false);
        editarButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Editar – 1.png"))); // NOI18N
        editarButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Editar – 1.png"))); // NOI18N
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 320, 100, 100));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/home.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        registroCarreraTable.setAutoCreateRowSorter(true);
        registroCarreraTable.setBackground(new java.awt.Color(255, 255, 250));
        registroCarreraTable.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        registroCarreraTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Carrera", "Facultad", "Carrera"
            }
        ));
        jScrollPane1.setViewportView(registroCarreraTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 1150, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Visualizar carrera – 1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        MenuAdministrador MenuAdmin = new MenuAdministrador();
        this.setVisible(false);
        MenuAdmin.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        this.setVisible(false);
        agregar.setVisible(true);
        refrescarTabla();
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        try {
            int filaSeleccionada = registroCarreraTable.getSelectedRow();
            if (filaSeleccionada == -1) {
                return;
            }
            String nombreCarrera = (String) registroCarreraTable.getValueAt(filaSeleccionada, 1);
            ICarrera carrera = RMI.getICarreraController().findOne(nombreCarrera);
            if (carrera.getIdCarrera() == 0) {
                JOptionPane.showMessageDialog(this,
                        "Carrera no encontrada.\n"
                        + "Es probable que la carrera haya sido eliminada previamente",
                        "Carrera no encontrada",
                        JOptionPane.ERROR_MESSAGE);
                refrescarTabla();
                return;
            }

            EditarCarrera editarCarrera = new EditarCarrera(carrera);
            this.setVisible(false);
            editarCarrera.setVisible(true);
            refrescarTabla();
        } catch (RemoteException ex) {
            Logger.getLogger(CarrerasRegistradas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        try {
            int filaSeleccionada = registroCarreraTable.getSelectedRow();
            if (filaSeleccionada == -1) {
                return;
            }
            int confirmacion = JOptionPane.showConfirmDialog(this,
                    "Usted está a punto de eliminar una carrera\n"
                    + "¿Desea continuar?",
                    "¿ELiminar carrera?",
                    JOptionPane.YES_NO_OPTION);
            if (confirmacion != JOptionPane.YES_OPTION) {
                return;
            }

            String Carrera = (String) registroCarreraTable.getValueAt(filaSeleccionada, 1);
            int respuesta = RMI.getICarreraController().delete(Carrera);

            if (respuesta == ICarreraController.DELETE_EXITO) {
                JOptionPane.showMessageDialog(
                        this,
                        "Carrera eliminada con éxito.",
                        "Operación éxitosa",
                        JOptionPane.INFORMATION_MESSAGE);
                refrescarTabla();
            } else if (respuesta == ICarreraController.DELETE_ID_INEXISTENTE) {
                JOptionPane.showMessageDialog(
                        this,
                        "Carrera no encontrada.\n"
                        + "Es posible que la carrera haya sido eliminada previamente",
                        "Carrera no encontrada",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Operación incompleta.\nNo fue posible eliminar la carrera",
                        "Operación incompleta",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (RemoteException ex) {
            Logger.getLogger(CarrerasRegistradas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarrerasRegistradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarrerasRegistradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarrerasRegistradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarrerasRegistradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }



        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarrerasRegistradas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable registroCarreraTable;
    // End of variables declaration//GEN-END:variables
}
