/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;

/**
 *
 * @author adria
 */
public class MenuAdministrador extends javax.swing.JFrame {

    
    public MenuAdministrador() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/media/logo.png")).getImage());
        this.setLocationRelativeTo(null);
        
    }

    SecretariasRegistradas registroSecre = new SecretariasRegistradas();
    FacultadesRegistradas registroFac = new FacultadesRegistradas();
    Reportes reporte = new Reportes();
    ImprimirCredenciales imprimir = new ImprimirCredenciales();
    CarrerasRegistradas carreras = new CarrerasRegistradas();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        secretariasRegistradasButton = new javax.swing.JButton();
        imprimirCredencialButton = new javax.swing.JButton();
        facultadesRegistradasButton = new javax.swing.JButton();
        generarReportesButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        carrerasRegistradasButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        secretariasRegistradasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Bot1.png"))); // NOI18N
        secretariasRegistradasButton.setBorder(null);
        secretariasRegistradasButton.setContentAreaFilled(false);
        secretariasRegistradasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secretariasRegistradasButtonActionPerformed(evt);
            }
        });
        getContentPane().add(secretariasRegistradasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 380, 250));

        imprimirCredencialButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Bot1 – 2.png"))); // NOI18N
        imprimirCredencialButton.setBorder(null);
        imprimirCredencialButton.setContentAreaFilled(false);
        imprimirCredencialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirCredencialButtonActionPerformed(evt);
            }
        });
        getContentPane().add(imprimirCredencialButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 140, 380, 250));

        facultadesRegistradasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Bot1 – 3.png"))); // NOI18N
        facultadesRegistradasButton.setBorder(null);
        facultadesRegistradasButton.setContentAreaFilled(false);
        facultadesRegistradasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultadesRegistradasButtonActionPerformed(evt);
            }
        });
        getContentPane().add(facultadesRegistradasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 380, 250));

        generarReportesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Bot1 – 1.png"))); // NOI18N
        generarReportesButton.setBorder(null);
        generarReportesButton.setContentAreaFilled(false);
        generarReportesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarReportesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(generarReportesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 380, 250));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Aviso de privacidad");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 670, -1, -1));

        carrerasRegistradasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Bot1 – 4.png"))); // NOI18N
        carrerasRegistradasButton.setBorder(null);
        carrerasRegistradasButton.setContentAreaFilled(false);
        carrerasRegistradasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrerasRegistradasButtonActionPerformed(evt);
            }
        });
        getContentPane().add(carrerasRegistradasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 380, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Menú Administrador – 2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imprimirCredencialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirCredencialButtonActionPerformed
        this.setVisible(false);
        imprimir.setVisible(true);
    }//GEN-LAST:event_imprimirCredencialButtonActionPerformed

    private void secretariasRegistradasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secretariasRegistradasButtonActionPerformed
        this.setVisible(false);
        registroSecre.setVisible(true);
    }//GEN-LAST:event_secretariasRegistradasButtonActionPerformed

    private void generarReportesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarReportesButtonActionPerformed
        this.setVisible(false);
        reporte.setVisible(true);
    }//GEN-LAST:event_generarReportesButtonActionPerformed

    private void facultadesRegistradasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultadesRegistradasButtonActionPerformed
        this.setVisible(false);
        registroFac.setVisible(true);
    }//GEN-LAST:event_facultadesRegistradasButtonActionPerformed

    private void carrerasRegistradasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrerasRegistradasButtonActionPerformed
        this.setVisible(false);
        carreras.setVisible(true);
    }//GEN-LAST:event_carrerasRegistradasButtonActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try {
            File path = new File(System.getProperty("user.dir") + "\\SICAUV_AvisoPrivacidad.pdf");
            Desktop.getDesktop().open(path);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carrerasRegistradasButton;
    private javax.swing.JButton facultadesRegistradasButton;
    private javax.swing.JButton generarReportesButton;
    private javax.swing.JButton imprimirCredencialButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton secretariasRegistradasButton;
    // End of variables declaration//GEN-END:variables
}
